#ifndef HOST_STUB_ACTION_SCHEDULER_4DOF_H
#define HOST_STUB_ACTION_SCHEDULER_4DOF_H

#include <stdbool.h>

#include "Dof4_Arm.h"

typedef enum {
    ACTION_4DOF_IDLE = 0,
    ACTION_BLOCK_GET_FORWARD = 1,
    ACTION_BLOCK_GET_FORWARD_LEFT_ARM = 2,
    ACTION_BLOCK_GET_FORWARD_RIGHT_ARM = 3,
    ACTION_BLOCK_PLACE_BACK = 4,
    ACTION_BLOCK_PLACE_LEFT_ARM_TO_LEFT_BACK = 5,
    ACTION_BLOCK_PLACE_RIGHT_ARM_TO_RIGHT_BACK = 6,
    ACTION_BLOCK_PLACE_LEFT_ARM_TO_LEFT_POINT1_F1 = 7,
    ACTION_BLOCK_PLACE_LEFT_ARM_TO_LEFT_POINT1_F2 = 8,
    ACTION_BLOCK_PLACE_RIGHT_ARM_TO_RIGHT_POINT1_F1 = 9,
    ACTION_BLOCK_PLACE_RIGHT_ARM_TO_RIGHT_POINT1_F2 = 10,
    ACTION_BLOCK_GET_LEFT_BACK_TO_HAND_LEFT_ARM = 11,
    ACTION_BLOCK_GET_RIGHT_BACK_TO_HAND_RIGHT_ARM = 12,
    ACTION_DANCE = 13,
} action_state_4dof_e;

typedef enum {
    ACTION_4DOF_SUBSTATE_IDLE = 0,
    ACTION_4DOF_SUBSTATE_APPROACH,
    ACTION_4DOF_SUBSTATE_INTERMEDIATE,
    ACTION_4DOF_SUBSTATE_GRAB,
    ACTION_4DOF_SUBSTATE_SUCTION_CONTROL_GRAB,
    ACTION_4DOF_SUBSTATE_RETREAT,
    ACTION_4DOF_SUBSTATE_COMPLETE,
    ACTION_4DOF_SUBSTATE_PLACE_APPROACH,
    ACTION_4DOF_SUBSTATE_PLACE,
    ACTION_4DOF_SUBSTATE_SUCTION_CONTROL_PLACE,
    ACTION_4DOF_SUBSTATE_WAYPOINT,
} action_4dof_substate_e;

typedef struct {
    bool left_back;
    bool right_back;
} BlockPlacementState;

#define IDLE_BASE_X      0.15f
#define IDLE_BASE_Y      0.00f
#define IDLE_BASE_Z      0.05f
#define IDLE_BASE_PITCH -0.55f

bool action_4dof_is_active(void);
bool action_4dof_trigger(action_state_4dof_e action);
void action_4dof_abort(void);
Dof4_Pose action_4dof_get_idle_pose(Dof4_ArmId arm_id);
void action_4dof_set_back_occupied(Dof4_ArmId arm_id, bool occupied);

#endif
